### ISSUE TITLE
Login with custom apps not works

### ISSUE THREAD

**Issue by patou** [hgwood/petibrugnon#15]
First I create a new client id on a google cloud projet.
I create a Oauth Client ID, choose the desktop application type (I don't find mobile app type, android or ios type ask package name), and save the client id.

Then I use the login commande : 
`node src/cli.js "login" "--cid" "xxxx.apps.googleusercontent.com" `

I open the link, login with my email account, and have this error :

Erreur 403 : access_denied
The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer (zero[...]@gmail.com).

Si vous êtes le développeur de l'appli, assurez-vous que les détails de cette requête respectent les règles de Google.
response_type: code
redirect_uri: urn:ietf:wg:oauth:2.0:oob
client_id: 226377176553-xxx.apps.googleusercontent.com
access_type: offline
scope: https://www.googleapis.com/auth/codejam

**Comment by hgwood** [comment]
Thanks!

There are two problems here:
- The `--cid` is not actually used so my hard coded client is always used
- For clients in test mode (like mine), users must be authorized to use it individually, and you are not authorized. This should be documented in the README but it is not.

I'm going to fix both.

**Comment by hgwood** [comment]
All done!
